# 配置tomcat端口号
server:
  port: 8080



# 配置数据源
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/beetl?characterEncoding\=UTF-8&amp;autoReconnect\=true
    type: com.alibaba.druid.pool.DruidDataSource

    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 600000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 60000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return:  false
    pool-prepared-statements: true
    filters: stat,wall,log4j
    max-pool-prepared-statement-per-connection-size: 20
    use-global-data-source-stat: true
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

## 配置mybatis
mybatis:
#  # 配置类型别名包扫描
#  type-aliases-package: com.xxx.xxx.pojo
#  # 配置sql语句映射文件路径
#  mapper-locations:
#    - classpath:mappers/*.xml
#  # 驼峰映射
  configuration:
    map-underscore-to-camel-case: true


# 配置日志
logging:
  level:
    com.xxx: debug